### ISSUE TITLE
Sound tag extraction completely broken on some setups

### ISSUE THREAD

**Issue by ShellyHerself** [MosesofEgypt/reclaimer#47]
![](https://cdn.discordapp.com/attachments/577227356918513665/675104087800545300/unknown.png)

@MosesofEgypt 

I can't even find the place where it modifies sound tags on extraction.

Please help

**Comment by ShellyHerself** [comment]
tags\sound\dialog\multiplayer1\team_race.sound

**Comment by ShellyHerself** [comment]
![Screenshot_20200207_001102](https://user-images.githubusercontent.com/24233409/73986619-591b9000-493e-11ea-8786-e22f98b2f340.png)
original vs extracted

**Comment by MosesofEgypt** [comment]
Just now extracted it from vanilla custom edition timberland with refinery 2.3.0 and loaded it in mozzarilla. It works just fine for me. Could this be related to the sound extraction change you were proposing, where you were wanting to change "ignore_rsrc_sounds" here?
https://github.com/Sigmmma/reclaimer/blob/master/reclaimer/meta/wrappers/halo1_map.py#L370

**Comment by ShellyHerself** [comment]
This is a problem with the latest public version. That never had that change applied.

**Comment by ShellyHerself** [comment]
I'm having the person test with the beta mek installer right now.

(And they still have this issue.) Python 3.8

**Comment by MosesofEgypt** [comment]
I'm using the current master branches for everything(except I'm on develop for refinery and supyr, but that only have one unrelated commit each). I don't know where our difference is

**Comment by ShellyHerself** [comment]
It's also only this sound tag for them

**Comment by MosesofEgypt** [comment]
How big is the map he's extracting from? over 2GB?

**Comment by MosesofEgypt** [comment]
How about his sounds resource map? is that over 2GB?

**Comment by MosesofEgypt** [comment]
Because I know about this bug occurring if any of the pointers would try to reference something outside the 2GB address space.

**Comment by ShellyHerself** [comment]
He seems to be using a vanilla sound map. And seems to be having this issues with any map he's extracting. This was from tutorial.map, but Idk what tutorial.map

**Comment by MosesofEgypt** [comment]
Okay well, there is not enough information for me to go on here. I'll need to talk with him directly.

**Comment by ShellyHerself** [comment]
[tutorial.map.zip](https://github.com/Sigmmma/reclaimer/files/4168251/tutorial.map.zip)

Same error with stock sound map.

**Comment by ShellyHerself** [comment]
![unknown](https://user-images.githubusercontent.com/24233409/73987739-a3ead700-4941-11ea-9fba-d51ad5142807.png)

**Comment by ShellyHerself** [comment]
Fixed this a few releases ago
